---
kind: Template
apiVersion: v1
metadata:
  name: missing-objects
message: |-
          the following objects will be created:
          
              Route: secure-${APPLICATION_NAME}-smartrouter
              
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  required: true
objects:
- kind: Route
  apiVersion: v1
  id: "${APPLICATION_NAME}-smartrouter-https"
  metadata:
    name: "secure-${APPLICATION_NAME}-smartrouter"
    labels:
      application: "${APPLICATION_NAME}"
      service: "${APPLICATION_NAME}-smartrouter"
      rhpam: "1.1"
    annotations:
      description: Route for Smart Router's https service.
  spec:
    host: ""
    to:
      name: "${APPLICATION_NAME}-smartrouter"
    port:
      targetPort: https
    tls:
      termination: passthrough
