---
kind: Template
apiVersion: v1
metadata:
  name: missing-objects
message: |-
          the following objects will be created:
          
              Service Account: ${APPLICATION_NAME}-kieserver
              Role Binding: ${APPLICATION_NAME}-kieserver-edit
              
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  required: true
objects:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-kieserver"
    labels:
      application: "${APPLICATION_NAME}"
      rhpam: "1.1"
- kind: RoleBinding
  apiVersion: v1
  metadata:
     name: "${APPLICATION_NAME}-kieserver-edit"
     labels:
       application: "${APPLICATION_NAME}"
       rhpam: "1.1"
  subjects:
  - kind: ServiceAccount
    name: "${APPLICATION_NAME}-kieserver"
  roleRef:
    name: edit
