---
kind: Template
apiVersion: v1
metadata:
  name: missing-objects
message: |-
          the following objects will be created:
          
              Service Account: ${APPLICATION_NAME}-rhpamsvc
              Service Account: ${APPLICATION_NAME}-kieserver
              Role Binding: ${APPLICATION_NAME}-rhpamsvc-edit
              Role Binding: ${APPLICATION_NAME}-kieserver-edit
              Route: secure-${APPLICATION_NAME}-smartrouter
              
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  required: true
objects:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-rhpamsvc"
    labels:
      application: "${APPLICATION_NAME}"
- kind: RoleBinding
  apiVersion: v1
  metadata:
     name: "${APPLICATION_NAME}-rhpamsvc-edit"
     labels:
       application: "${APPLICATION_NAME}"
  subjects:
  - kind: ServiceAccount
    name: "${APPLICATION_NAME}-rhpamsvc"
  roleRef:
    name: edit
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-kieserver"
    labels:
      application: "${APPLICATION_NAME}"
- kind: RoleBinding
  apiVersion: v1
  metadata:
     name: ""
     labels:
       application: "${APPLICATION_NAME}"
  subjects:
  - kind: ServiceAccount
    name: "${APPLICATION_NAME}-kieserver"
  roleRef:
    name: edit
- kind: Route
  apiVersion: v1
  id: "${APPLICATION_NAME}-smartrouter-https"
  metadata:
    name: "secure-${APPLICATION_NAME}-smartrouter"
    labels:
      application: "${APPLICATION_NAME}"
      service: "${APPLICATION_NAME}-smartrouter"
    annotations:
      description: Route for Smart Router's https service.
  spec:
    host: ""
    to:
      name: "${APPLICATION_NAME}-smartrouter"
    port:
      targetPort: https
    tls:
      termination: passthrough
